#!/bin/bash
set -e

if ! snapctl is-connected graphics-core20; then
  echo "ERROR: You need to connect the graphics-core20 interface."
  echo "e.g. sudo snap connect $SNAP_INSTANCE_NAME:graphics-core20 mesa-core20:graphics-core20"
  exit 1
fi

mkdir -p "$XDG_RUNTIME_DIR" -m 700

if [ -v MIR_SERVER_WAYLAND_HOST ]; then
  MIR_SERVER_CONSOLE_PROVIDER=${MIR_SERVER_CONSOLE_PROVIDER:-none}
  export MIR_SERVER_CONSOLE_PROVIDER
  host_wayland=$(dirname "${XDG_RUNTIME_DIR}")/${MIR_SERVER_WAYLAND_HOST}
  if [ ! -O "${host_wayland}" ] || [ ! -O "${host_wayland}.lock" ]; then
    echo "ERROR: MIR_SERVER_WAYLAND_HOST [${MIR_SERVER_WAYLAND_HOST}] set, but not available"
    exit 1
  fi
  ln -sf "${host_wayland}" "$XDG_RUNTIME_DIR"
  ln -sf "${host_wayland}.lock" "$XDG_RUNTIME_DIR"
elif [ -v DISPLAY ] && ! snapctl is-connected x11; then
  echo "ERROR: DISPLAY [${DISPLAY}] set, but you need to connect the x11 interface"
  echo "Try: sudo snap connect $SNAP_INSTANCE_NAME:x11"
  exit 1
elif [ $(id -u) != 0 ] && ! [ -v DISPLAY ] && ! snapctl is-connected login-session-control; then
  echo "ERROR: You need one of:"
  echo "  1. An X11 host specified by DISPLAY environment variable"
  echo "  2. The login-session-control interface connected"
  echo "     Try: sudo snap connect $SNAP_INSTANCE_NAME:login-session-control"
  echo "  3. Root (run with sudo)"
  echo "  4. A Wayland host specified by MIR_SERVER_WAYLAND_HOST environment variable"
  exit 1
fi

# Use hack in snapd for proprietary nVidia drivers mounts the drivers in
# /var/lib/snapd/lib/gl that needs to be in LD_LIBRARY_PATH
# Without that OpenGL using apps do not work with the nVidia drivers
if [ -d /var/lib/snapd/lib/glvnd/egl_vendor.d ]; then
  __EGL_VENDOR_LIBRARY_DIRS=/var/lib/snapd/lib/glvnd/egl_vendor.d:${__EGL_VENDOR_LIBRARY_DIRS}
  LD_LIBRARY_PATH=/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl/vdpau:${LD_LIBRARY_PATH}
fi

# This ensures the best possible diagnostics whenever we fail to start.
export MIR_MESA_KMS_DISABLE_MODESET_PROBE=
unset WAYLAND_DISPLAY

# Use any quirks the driver needs
mkdir -p "${XDG_CONFIG_HOME}/mir"
ln -sf "${SNAP}/graphics/etc/mir-quirks" "${XDG_CONFIG_HOME}/mir/mir_demo_server.config"

exec "$@"
