#!/bin/bash
set -e

if [ $(id -u) != 0 ] && ! [ -v DISPLAY ] && ! snapctl is-connected login-session-control; then
  echo "ERROR: You need one of: root, a DISPLAY, or to connect the login-session-control interface."
  echo "e.g. sudo snap connect" $SNAP_NAME":login-session-control :login-session-control"
  exit 1
fi

mkdir -p "$XDG_RUNTIME_DIR" -m 700
# This ensures the best possible diagnostics whenever we fail to start.
export MIR_MESA_KMS_DISABLE_MODESET_PROBE=
unset WAYLAND_DISPLAY

exec "$@"
