#!/bin/bash
set -e

if [ $(id -u) != 0 ] && ! [ -v DISPLAY ] && ! snapctl is-connected login-session-control; then
  echo "ERROR: You need one of: root, a DISPLAY, or to connect the login-session-control interface."
  echo "e.g. sudo snap connect" $SNAP_NAME":login-session-control :login-session-control"
  exit 1
fi

mkdir -p "$XDG_RUNTIME_DIR" -m 700

if [ -v MIR_SERVER_WAYLAND_HOST ]; then
  MIR_SERVER_CONSOLE_PROVIDER=${MIR_SERVER_CONSOLE_PROVIDER:-none}
  export MIR_SERVER_CONSOLE_PROVIDER
  host_wayland=$(dirname "${XDG_RUNTIME_DIR}")/${MIR_SERVER_WAYLAND_HOST}
  if [ ! -O "${host_wayland}" ] || [ ! -O "${host_wayland}.lock" ]; then
    echo "ERROR: MIR_SERVER_WAYLAND_HOST [${MIR_SERVER_WAYLAND_HOST}] not set up"
    exit 1
  fi
  ln -sf "${host_wayland}" "$XDG_RUNTIME_DIR"
  ln -sf "${host_wayland}.lock" "$XDG_RUNTIME_DIR"
fi

# This ensures the best possible diagnostics whenever we fail to start.
export MIR_MESA_KMS_DISABLE_MODESET_PROBE=
unset WAYLAND_DISPLAY

exec "$@"
