name: mir-test-tools
adopt-info: mir-test-tools
summary: Mir test scripts and applications
description: Mir test scripts and applications
confinement: strict
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: riscv64

package-repositories:
  - type: apt
    ppa: mir-team/release
  - type: apt
    ppa: graphics-drivers/ppa

environment:
  LC_ALL: C.UTF-8
  XCURSOR_PATH: $SNAP/usr/share/icons
  # XDG config
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config
  XDG_DATA_HOME:   $SNAP_USER_DATA
  XDG_DATA_DIRS:   $SNAP/usr/share
  XDG_CONFIG_DIRS: $SNAP/etc/xdg
  XDG_CACHE_HOME:  $SNAP_USER_COMMON/.cache
  # Prep for Mir
  MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET}/mir/server-platform

apps:
  smoke-test:
    command-chain:
      - bin/wrapper
      - bin/graphics-core22-wrapper
    command: usr/bin/mir-smoke-test-runner

  # SDL2 example
  sdl2-test:
    command-chain:
      - bin/wrapper
      - bin/graphics-core22-wrapper
    command: usr/bin/mir_demo_server --test-client neverputt
    plugs:
      - pulseaudio
    environment:
      # Alsa config
      ALSA_CONFIG_DIR: $SNAP/usr/share/alsa
      ALSA_CONFIG_PATH: ${SNAP}/usr/share/alsa
      ALSA_MIXER_SIMPLE: ${SNAP}/usr/share/alsa
      # SDL config
      PATH: $SNAP/bin/:$SNAP/usr/bin/:${SNAP}/usr/games:${PATH}
      NEVERBALL_DATA: $SNAP/usr/share/games/neverball/

  # Qt example
  qt-test:
    command-chain:
      - bin/wrapper
      - bin/graphics-core22-wrapper
    command: usr/bin/mir_demo_server --test-client $SNAP/qml/spinning-rect.sh
    environment:
      # Prep for Qt wayland
      QT_PLUGIN_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET}/qt5/plugins/
      QT_QPA_PLATFORM_PLUGIN_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET}/qt5/plugins/platforms/
      QML2_IMPORT_PATH: ${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET}/qt5/qml

  # GTK3+ example
  gtk3-test:
    command-chain:
      - bin/wrapper
      - bin/graphics-core22-wrapper
    command: usr/bin/mir_demo_server --test-client $SNAP/gtkapp.sh
    environment:
      PATH: $SNAP/bin/:$SNAP/usr/bin/:${SNAP}/usr/games:${PATH}

  performance-test:
    command-chain:
      - bin/performance-env.sh
      - bin/wrapper
      - bin/graphics-core22-wrapper
    command: usr/bin/mir_performance_tests
    plugs:
      - network-bind

plugs:
  # For Mir
  opengl:
  x11:
  login-session-control:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22

slots:
  wayland:

layout:
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0
  /usr/share/glmark2:
    symlink: $SNAP/usr/share/glmark2
  /usr/share/drirc.d:  # Used by mesa-core22 for app specific workarounds
    symlink: $SNAP/graphics/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/graphics/X11/XErrorDB
  /usr/share/X11/locale:
    symlink: $SNAP/graphics/X11/locale
  /usr/share/X11/xkb:
    symlink: $SNAP/usr/share/X11/xkb
  /usr/bin/Xwayland:
    symlink: $SNAP/usr/bin/Xwayland
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/lib/${CRAFT_ARCH_TRIPLET}/pulseaudio:
    symlink: $SNAP/usr/lib/${CRAFT_ARCH_TRIPLET}/pulseaudio
  # these could be avoided through a desktop plug
  /etc/gtk-3.0:
    bind: $SNAP/etc/gtk-3.0
  /etc/fonts:
    bind: $SNAP/etc/fonts

parts:
  mir-test-tools:
    plugin: nil
    override-build: |
      craftctl default
      mir_version=`LANG=C apt-cache policy mir-test-tools | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
      recipe_version=`git -C ${CRAFT_PROJECT_DIR} rev-list --count HEAD`
      craftctl set version=$mir_version-snap$recipe_version
      if echo $mir_version | grep -e '+dev' -e '~rc' -q; then craftctl set grade=devel; else craftctl set grade=stable; fi
    stage-packages:
    - fonts-freefont-ttf
    - mir-graphics-drivers-desktop
    - mir-test-tools
    - glmark2-es2
    - glmark2-data
    - glmark2-es2-wayland
    - on amd64: [mir-graphics-drivers-nvidia]

  icons:
    plugin: nil
    stage-packages: [dmz-cursor-theme]

  sdl2-apps:
    plugin: nil
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libsdl2-net-2.0-0
      - libpulse0
      # SDL2 games
      - neverputt

  qmldemo:
    plugin: dump
    source: qmldemo
    stage-packages:
      - qmlscene
      - qtwayland5
      - qml-module-qtquick2
    organize:
      spinning-rect.qml: qml/spinning-rect.qml
      spinning-rect.sh: qml/spinning-rect.sh

  gtk3app:
    plugin: dump
    source: gtk3
    override-build: |
      craftctl default
      update-mime-database $CRAFT_PART_INSTALL/usr/share/mime
    stage-packages:
      - gnome-sudoku
    build-packages: # These are actually for override-prime - which needs them in the build environment
      - libglib2.0-0
      - libgdk-pixbuf2.0-0
      - librsvg2-dev # So the libpixbufloader-svg.so loader can be loaded by gdk-pixbuf-query-loaders
    override-prime: |
      craftctl default
      # Compile the gsettings schemas
      /usr/lib/${CRAFT_ARCH_TRIPLET}/glib-2.0/glib-compile-schemas "$CRAFT_PRIME/usr/share/glib-2.0/schemas"
      # Index the pixbuf loaders
      GDK_PIXBUF_MODULEDIR=$CRAFT_PRIME/usr/lib/${CRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/2.10.0/loaders \
      "/usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders" > "$CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders.cache"
      sed s!$CRAFT_PRIME!!g --in-place "$CRAFT_PRIME/usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-2.0/2.10.0/loaders.cache"

  performance:
    plugin: dump
    source: performance
    organize:
      performance-env.sh: bin/performance-env.sh

  wrapper:
    plugin: dump
    source: wrapper
    organize:
      wrapper: bin/wrapper

  xwayland:
    plugin: nil
    stage-packages:
      - xwayland
      - libbz2-1.0

  graphics-core22:
    after: [mir-test-tools, icons, sdl2-apps, qmldemo, gtk3app, performance, wrapper, xwayland]
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22
    prime:
      - bin/graphics-core22-wrapper
