name: Close Snaps

on:
  pull_request:
    types: [closed]

jobs:
  close:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
      with:
        snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN }}

    - name: Close obsolete channels
      run: snapcraft close mir-test-tools "edge/pr${{ github.event.number }}" || true
