#!/bin/bash
set -x

if [ ! -d  "$SNAP_DATA/.config/mir" ]; then
   mkdir -p $SNAP_DATA/.config/mir
fi

if [ ! -d "$SNAP_DATA/.xdg_runtime_dir" ]; then
   mkdir   $SNAP_DATA/.xdg_runtime_dir
fi

if [ ! -d "$SNAP_DATA/.cache" ]; then
   mkdir   $SNAP_DATA/.cache
fi
